/**
 * Red Flag Detector
 * Detects suspicious patterns in email headers.
 * Inspired by Sublime Security's detection rule taxonomy.
 * Client-side only — pure TypeScript, zero dependencies.
 */

import type { ParsedHeader, RedFlag } from './types';
import { getHeader, getHeaders } from './header-parser';

const BULK_PLATFORMS = ['mailchimp', 'sendgrid', 'mailgun', 'constantcontact', 'sendinblue', 'postmark'];

export function detectRedFlags(headers: ParsedHeader[]): RedFlag[] {
  const flags: RedFlag[] = [];

  // --- Bulk mail indicators ---
  const xCampaign = getHeader(headers, 'X-Campaignid') || getHeader(headers, 'X-Campaign');
  if (xCampaign) {
    flags.push({
      category: 'bulk-mail',
      header: 'X-Campaignid',
      value: xCampaign,
      severity: 'low',
      riskScore: 5,
      description: 'Marketing campaign identifier detected',
      explanation: "This email was sent as part of a marketing campaign. If you didn't subscribe, this could be unsolicited bulk mail.",
    });
  }

  const precedence = getHeader(headers, 'Precedence');
  if (precedence && /^(bulk|list)$/i.test(precedence.trim())) {
    flags.push({
      category: 'bulk-mail',
      header: 'Precedence',
      value: precedence,
      severity: 'low',
      riskScore: 5,
      description: 'Email identifies itself as bulk/list mail',
      explanation: 'This email identifies itself as bulk/list mail. Legitimate marketing uses this, but so do mass phishing campaigns.',
    });
  }

  const listUnsub = getHeader(headers, 'List-Unsubscribe');
  if (listUnsub) {
    flags.push({
      category: 'bulk-mail',
      header: 'List-Unsubscribe',
      value: listUnsub,
      severity: 'low',
      riskScore: 5,
      description: 'Mass mailing unsubscribe link present',
      explanation: 'This email includes an unsubscribe mechanism typical of mass mailings.',
    });
  }

  const xMailer = getHeader(headers, 'X-Mailer');
  if (xMailer) {
    const lowerMailer = xMailer.toLowerCase();
    const platform = BULK_PLATFORMS.find((p) => lowerMailer.includes(p));
    if (platform) {
      flags.push({
        category: 'bulk-mail',
        header: 'X-Mailer',
        value: xMailer,
        severity: 'low',
        riskScore: 5,
        description: `Sent via mass-mailing platform: ${platform}`,
        explanation: `This email was sent through a mass-mailing platform: ${platform}. While many legitimate businesses use these, so do phishing campaigns.`,
      });
    }
  }

  // --- Missing standard headers ---
  if (!getHeader(headers, 'Message-ID')) {
    flags.push({
      category: 'missing-headers',
      header: 'Message-ID',
      severity: 'medium',
      riskScore: 10,
      description: 'Missing Message-ID header',
      explanation: 'This email is missing a Message-ID, which is required by email standards. Legitimate mail servers always generate one. Missing Message-IDs can indicate the email was crafted manually by an attacker.',
    });
  }

  if (!getHeader(headers, 'Date')) {
    flags.push({
      category: 'missing-headers',
      header: 'Date',
      severity: 'medium',
      riskScore: 10,
      description: 'Missing Date header',
      explanation: 'This email is missing a Date header. All legitimate email includes a timestamp. This could indicate a manually crafted phishing email.',
    });
  }

  if (!getHeader(headers, 'MIME-Version')) {
    flags.push({
      category: 'missing-headers',
      header: 'MIME-Version',
      severity: 'medium',
      riskScore: 10,
      description: 'Missing MIME-Version header',
      explanation: "This email is missing the MIME-Version header. While not always suspicious on its own, combined with other missing headers it suggests the email wasn't generated by standard mail software.",
    });
  }

  // --- Suspicious origin ---
  const xOrigIP = getHeader(headers, 'X-Originating-IP');
  if (xOrigIP) {
    flags.push({
      category: 'suspicious-origin',
      header: 'X-Originating-IP',
      value: xOrigIP,
      severity: 'high',
      riskScore: 15,
      description: "Sender's real IP address exposed",
      explanation: "The sender's actual IP address is exposed in the headers. This is normal for webmail but can help identify the true origin of a suspicious email.",
    });
  }

  const exchangeAuth = getHeader(headers, 'X-MS-Exchange-Organization-AuthAs');
  if (exchangeAuth && exchangeAuth.toLowerCase() === 'anonymous') {
    flags.push({
      category: 'suspicious-origin',
      header: 'X-MS-Exchange-Organization-AuthAs',
      value: exchangeAuth,
      severity: 'high',
      riskScore: 15,
      description: 'Unauthenticated Exchange relay',
      explanation: 'This email was processed as unauthenticated by Microsoft Exchange. The sender did not authenticate with the mail server, which is a common trait of spoofed emails.',
    });
  }

  const spamFlag = getHeader(headers, 'X-Spam-Flag');
  const spamStatus = getHeader(headers, 'X-Spam-Status');
  if ((spamFlag && spamFlag.toUpperCase() === 'YES') || (spamStatus && spamStatus.toLowerCase().startsWith('yes'))) {
    flags.push({
      category: 'suspicious-origin',
      header: spamFlag ? 'X-Spam-Flag' : 'X-Spam-Status',
      value: spamFlag || spamStatus || undefined,
      severity: 'high',
      riskScore: 15,
      description: 'Already flagged as spam',
      explanation: 'This email was already flagged as spam by a mail server it passed through. Treat with caution.',
    });
  }

  // --- Encoding tricks ---
  const fromHeader = getHeader(headers, 'From');
  const subject = getHeader(headers, 'Subject');
  if ((fromHeader && /=\?(UTF-8|iso-8859)/i.test(fromHeader)) || (subject && /=\?(UTF-8|iso-8859)/i.test(subject))) {
    flags.push({
      category: 'encoding-tricks',
      header: fromHeader && /=\?/i.test(fromHeader) ? 'From' : 'Subject',
      severity: 'high',
      riskScore: 15,
      description: 'Encoded characters in sender or subject',
      explanation: 'The sender name or subject uses encoded characters. While encoding is normal for international text, it can be used to disguise the true content or sender identity.',
    });
  }

  const fromHeaders = getHeaders(headers, 'From');
  if (fromHeaders.length > 1) {
    flags.push({
      category: 'encoding-tricks',
      header: 'From',
      severity: 'high',
      riskScore: 15,
      description: 'Multiple From headers detected',
      explanation: 'This email has multiple From headers, which violates email standards. Some email clients may display one while security filters check another \u2014 a technique used to bypass phishing detection.',
    });
  }

  // --- Infrastructure ---
  const phpScript = getHeader(headers, 'X-PHP-Script') || getHeader(headers, 'X-PHP-Originating-Script');
  if (phpScript) {
    flags.push({
      category: 'infrastructure',
      header: 'X-PHP-Script',
      value: phpScript,
      severity: 'medium',
      riskScore: 10,
      description: 'Generated by PHP script',
      explanation: "This email was generated by a PHP script on a web server. While some legitimate systems send email this way, it's also common with compromised websites being used to send phishing emails.",
    });
  }

  const xSource = getHeader(headers, 'X-Source') || getHeader(headers, 'X-Source-Args');
  if (xSource) {
    flags.push({
      category: 'infrastructure',
      header: 'X-Source',
      value: xSource,
      severity: 'medium',
      riskScore: 10,
      description: 'Server debugging headers exposed',
      explanation: 'This email includes debugging headers that reveal how it was generated on the sending server. This can indicate it was sent from a compromised hosting account.',
    });
  }

  return flags;
}
